# yaml-language-server: $schema=https://blue-build.org
name: goblin
description: Celestial Uprising's Immutable Operating System
base-image: ghcr.io/celestial-uprising/rusty-ucore
image-version: latest
stages:
  - name: goblin
    from: quay.io/fedora/fedora:44
    modules:
      - type: copy
        src: files/goblin_install.md
        dest: /tmp/goblin_install.md
      - type: script
        snippets:
          - mkdir -p /tmp/bin
          - |
            dnf5 upgrade -y && dnf5 install -y golang git
            
            MD_FILE="/tmp/goblin_install.md"
            if [ ! -f "$MD_FILE" ]; then
              echo "Error: $MD_FILE not found!"
              exit 1
            fi
            
            while read -r line || [ -n "$line" ]; do
              case "$line" in
                *"go install"*)
                  echo "----------------------------------------"
                  echo "Executing: $line (outputting to /tmp/bin)"
                  env GOBIN=/tmp/bin $line
                  ;;
              esac
            done < "$MD_FILE"
modules:
  - type: os-release
    properties:
      VARIANT: "goblin"
  - type: copy
    from: goblin
    src: /tmp/bin/
    dest: /usr/bin/
