---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: framework-base
description: for all- by lesbidoodles ; with hope for a better future
base-image: ghcr.io/ublue-os/ucore
image-version: testing
modules:
  - type: os-release
    properties:
      NAME: "Celestial Uprising"
      PRETTY_NAME: "Celestial Uprising 44.20260829.2.3 (framework)"
      VERSION_CODENAME: "framework"
      ID_LIKE: fedora
      HOME_URL: "https://github.com/celestial-uprising/framework/"
      DOCUMENTATION_URL: "https://docs.fedoraproject.org/en-US/fedora-coreos/"
      SUPPORT_URL: "https://github.com/coreos/fedora-coreos-tracker/"
      BUG_REPORT_URL: "https://github.com/celestial-uprising/framework/"
      VARIANT: "base"
  - type: files
    files:
      - source: rpms/aocc-compiler-5.2.0-1.x86_64.rpm
        destination: /tmp/aocc-compiler.rpm
  - type: dnf
    repos:
      copr:
        - atim/lazygit
        - atim/starship
        - kylegospo/amdctl
    install:
      packages:
        - libquadmath
        - libquadmath-devel
        - lazygit
        - starship
        - power-profiles-daemon
        - fontconfig
        - mesa-dri-drivers
        - mesa-vulkan-drivers
        - vulkan-loader
        - vulkan-tools
        - libva-nvidia-driver
        - amdctl
        - cascadia-code-nf-fonts
        - glibc-langpack-en
        - libvirt-client
        - libvirt-client-qemu
        - neovim
        - fzf
        - fd-find
        - ripgrep
        - zoxide
        - bat
        - eza
        - luarocks
        - tree-sitter-cli
        - python3-neovim
        - btop
        - rocm-smi-devel
        - nvtop
        - radeontop
        - libdrm-devel
        - s-tui
        - tree
        - vim
        - git
        - wget
        - gdu
        - diskus
        - nmap
        - traceroute
        - whois
        - rustup
    remove:
      packages:
        - nano
        - nano-default-editor
        - nfs-client-utils
        - nfs-common-utils
        - azure-vm-utils
        - cockpit
        - cockpit-bridge
        - cockpit-ws
  - type: script
    snippets:
      - |
        #!/usr/bin/env bash

        echo "Installing AOCC Compiler..."
        rpm -ivh --nodigest --nosignature /tmp/aocc-compiler.rpm
        rm -f /tmp/aocc-compiler.rpm

        echo "Creating BASH aliases..."
        mkdir -p /etc/profile.d
        cat << 'EOF' > /etc/profile.d/distrobox-aliases.sh
        alias db="distrobox enter"
        alias dbc="distrobox create"
        alias l="ls -A"
        alias ll="ls -lAsH"
        alias pls="podman ps"
        alias plsa="podman ps -a"
        alias prm="podman rm"
        alias prmi="podman rmi"
        alias pstop="podman stop"
        alias prun="podman run"
        alias bb="bluebuild"
        alias bbb="bluebuild build --build-driver podman"
        alias bbbb="bluebuild build --build-driver podman $HOME/.src/framework/recipes/base.yml"
        EOF
  - type: fonts
    fonts:
      nerd-fonts:
        - VictorMono
