---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: framework-mini
description: for humans- by lesbidoodles ; with hope for a better future
base-image: ghcr.io/ublue-os/ucore
image-version: testing
stages:
  - from-file: include/rust_build.in
modules:
  - from-file: include/files.in
  - from-file: include/copy.in
  - from-file: include/dnf.in
  - from-file: include/flatpak.in
  - from-file: include/scripts.in

  - type: signing
