---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: framework-mini
description: for humans- by lesbidoodles ; with hope for a better future
base-image: ghcr.io/ublue-os/ucore
image-version: testing
stages:
  - name: yazi-builder
    from: docker.io/library/fedora:latest # Clean image to compile on
    modules:
      - type: script
        snippets:
          - |
            dnf install -y git gcc cargo

            git clone https://github.com/sxyazi/yazi.git /tmp/yazi
            cd /tmp/yazi
            cargo build --release --locked

            mkdir -p /tmp/bin
            cp target/release/yazi /tmp/bin/
            cp target/release/ya /tmp/bin/
  - name: herdr-builder
    from: docker.io/library/fedora:latest
    modules:
      - type: script
        snippets:
          - |
            dnf install -y git gcc protobuf-compiler

            curl --proto '=https' --tlsv1.2 -sSf https://rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"

            git clone https://github.com/herdrdev/herdr.git /tmp/herdr
            cd /tmp/herdr
            cargo build --release --locked

            mkdir -p /tmp/bin
            cp target/release/herdr /tmp/bin/
  - name: flyline-builder
    from: docker.io/library/fedora:latest
    modules:
      - type: script
        snippets:
          - |
            dnf install -y git gcc cargo

            git clone https://github.com/HalFrgrd/flyline.git /tmp/flyline
            cd /tmp/flyline
            cargo build --release --locked

            mkdir -p /tmp/bin
            cp target/release/flyline /tmp/bin/
  - name: uv-builder
    from: docker.io/library/fedora:latest
    modules:
      - type: script
        snippets:
          - |
            dnf install -y gcc cargo

            mkdir -p /tmp/bin
            CARGO_HOME=/tmp/cargo cargo install --root /tmp/build --locked uv

            cp /tmp/build/bin/uv* /tmp/bin/
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      copr:
        - atim/starship
        - yalter/niri
        - atim/lazygit
    install:
      packages:
        - lazygit
        - glibc-langpack-en
        - sddm-conf
        - sddm-wayland-generic
        - waybar
        - fuzzel
        - kitty
        - niri
        - vim
        - fzf
        - ripgrep
        - zoxide
        - fd-find
        - bat
        - eza
        - btop
        - nvtop
        - radeontop
        - starship
        - tree-sitter-cli
        - rocm-smi-devel
        - neovim
        - python3-neovim
        - wl-clipboard
        - luarocks
        - git
        - wget
        - s-tui
        - libdrm-devel
        - gdu
        - ncdu
        - tree
        - diskus
        - nmap
        - traceroute
        - whois
        - swaybg
        - flatpak
        - loupe
    remove:
      packages:
        - nano
        - alacritty
        - nano-default-editor
        - nfs-client-utils
        - nfs-common-utils
        - azure-vm-utils
        - cockpit
        - cockpit-bridge
        - cockpit-ws
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: # system flatpaks
          - net.codelogistics.webapps
          - net.waterfox.waterfox
          - org.virt_manager.virt-manager
      - scope: user
  - type: fonts
    fonts:
      url-fonts:
        - name: VictorMonoNerdFont
          url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.1/VictorMono.zip
  - type: copy
    from: yazi-builder
    src: /tmp/bin/yazi
    dest: /usr/bin/yazi
  - type: copy
    from: yazi-builder
    src: /tmp/bin/ya
    dest: /usr/bin/ya
  - type: copy
    from: herdr-builder
    src: /tmp/bin/herdr
    dest: /usr/bin/herdr
  - type: copy
    from: flyline-builder
    src: /tmp/bin/flyline
    dest: /usr/bin/flyline
  - type: copy
    from: uv-builder
    src: /tmp/bin/uv
    dest: /usr/bin/uv
  - type: copy
    from: uv-builder
    src: /tmp/bin/uvx
    dest: /usr/bin/uvx
  - type: copy
    from: uv-builder
    src: /tmp/bin/uvw
    dest: /usr/bin/uvw
  - type: script
    snippets:
      - |
        mkdir -p /etc/profile.d
        echo 'if [[ $- == *i* ]]; then eval "$(flyline init)"; fi' > /etc/profile.d/flyline.sh

        cat << 'EOF' > /etc/profile.d/distrobox-aliases.sh
        alias db="distrobox enter"
        alias dbc="distrobox create"
        EOF

        echo 'export STARSHIP_CONFIG=/etc/starship.toml' > /etc/profile.d/starship-env.sh
        echo 'eval "$(starship init bash)"' > /etc/profile.d/starship.sh
        starship preset jetpack -o /etc/starship.toml

  - type: signing
