---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: framework-mini
description: for humans- by lesbidoodles ; with hope for a better future
base-image: ghcr.io/ublue-os/ucore
image-version: testing
stages:
  - name: rust-build
    from: docker.io/library/fedora:latest
    modules:
      - type: script
        snippets:
          - |
            dnf install -y git gcc protobuf-compiler

            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"

            ZIG_VERSION="0.15.2"
            curl -sSL https://ziglang.org -o /tmp/zig.tar.xz
            tar -xf /tmp/zig.tar.xz -C /opt/
            ln -s /opt/zig-linux-x86_64-$ZIG_VERSION/zig /usr/local/bin/zig
            
            mkdir -p /tmp/bin
            
            git clone https://github.com/sxyazi/yazi.git /tmp/yazi
            cd /tmp/yazi && cargo build --release --locked
            cp target/release/ya* /tmp/bin/
            
            git clone https://github.com/herdrdev/herdr.git /tmp/herdr
            cd /tmp/herdr && cargo build --release --locked
            cp target/release/herdr /tmp/bin/
            
            git clone https://github.com/HalFrgrd/flyline.git /tmp/flyline
            cd /tmp/flyline && cargo build --release --locked
            cp target/release/flyline /tmp/bin/
            
            CARGO_HOME=/tmp/cargo cargo install --root /tmp/build uv
            cp /tmp/build/bin/uv* /tmp/bin/
modules:
  - from-file: include/files.yml

  - type: copy
    from: rust-build
    src: /tmp/bin/yazi
    dest: /usr/bin/yazi

  - type: copy
    from: rust-build
    src: /tmp/bin/ya
    dest: /usr/bin/ya

  - type: copy
    from: rust-build
    src: /tmp/bin/herdr
    dest: /usr/bin/herdr

  - type: copy
    from: rust-build
    src: /tmp/bin/flyline
    dest: /usr/lib/bash/flyline

  - type: copy
    from: rust-build
    src: /tmp/bin/uv
    dest: /usr/bin/uv

  - type: copy
    from: rust-build
    src: /tmp/bin/uvx
    dest: /usr/bin/uvx

  - type: copy
    from: rust-build
    src: /tmp/bin/uvw
    dest: /usr/bin/uvw

  - from-file: include/dnf.yml
  - from-file: include/flatpak.yml
  - from-file: include/scripts.yml

  - type: signing
