# yaml-language-server: \$schema=https://blue-build.org
name: base
description: Celestial Uprising's Immutable Operating System
base-image: ghcr.io/celestial-uprising/rusty-ucore
image-version: latest
modules: 
    - type: os-release
      properties:
        VARIANT: "base"
    - type: containerfile
      snippets:
        - COPY --from=ghcr.io/ublue-os/akmods:main-44 /rpms /tmp/rpms
        - COPY --from=ghcr.io/ublue-os/akmods:main-44 /kernel-rpms /tmp/rpms/kernel
        - RUN find /tmp/rpms
        - RUN rpm -q ublue-os-akmods-addons || dnf install -y /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm
    - type: kargs
      kargs:
        - amd_iommu=on
        - iommu=pt
        - kvm_amd.nested=1
        - split_lock_detect=off
        - transparent_hugepage=always
        - kvm.ignore_msrs=1
        - net.ifnames=0
        - tcp_congestion_control=bbr
        - msr.allow_writes=on
    - type: dnf
      repos:
        copr:
          - lihaohong/yazi
          - atim/bottom
          - atim/gping
          - atim/lazygit
          - atim/starship
          - kylegospo/amdctl
          - greg-at-redhat/glowm
      install:
        install-weak-deps: false
        packages:
          - tailscale
          - yazi
          - bottom
          - gping
          - gitui
          - libvirt-client
          - libvirt-client-qemu
          - tree
          - chromium-headless
          - glowm
          - lazygit
          - starship
          - amdctl
          - cascadia-code-nf-fonts
          - neovim
          - fd-find
          - ripgrep
          - zoxide
          - bat
          - eza
          - luarocks
          - tree-sitter-cli
          - python3-neovim
          - btop
          - gdu
          - wget
          - git
          - diskus
          - nmap
          - traceroute
          - whois
          - rustup
          - powerstat
          - fzf
          - ddcutil
          - openssl
          - distrobox
      remove:
        packages:
          - firefox
          - nano
          - nano-default-editor
          - nfs-client-utils
          - nfs-common-utils
          - azure-vm-utils
          - cockpit
          - cockpit-bridge
          - cockpit-ws
    - type: files
      files:
        - source: system/usr
          destination: /usr
        - source: system/etc
          destination: /etc
    - type: fonts
      fonts:
        nerd-fonts:
          - VictorMono
    - type: script
      scripts:
        - regenerateinitramfs.sh
    - type: wayblue-signing
      source: local
