tty = 2
do_log = true
log_path = "/var/log/lemurs.log"
auto_username = true
focus_password_on_username_select = true
password_replace_char = "•"
poweroff_cmd = "$fallback_poweroff"
reboot_cmd = "$fallback_reboot"

[ui]
border_style = "rounded"
box_color = "$highlight"
text_color = "$text"
subtext_color = "$subtext"
highlight_color = "$highlight"
error_color = "$error"
background_color = "$background"

[wms]
default_env = "Wayland"
wayland_directory = "/etc/lemurs/wayland"
x11_directory = "/etc/lemurs/wms"
include_shell = true

