---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: framework-virt-nv
description: for humans- by lesbidoodles ; with hope for a better future
base-image: ghcr.io/ublue-os/ucore
image-version: testing-nvidia
stages:
  - name: rust-build
    from: docker.io/library/fedora:latest
    modules:
      - type: script
        snippets:
          - |
            dnf install -y git gcc protobuf-compiler

            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"

            mkdir -p /tmp/bin
            
            git clone https://github.com/sxyazi/yazi.git /tmp/yazi
            cd /tmp/yazi && cargo build --release --locked
            cp target/release/ya* /tmp/bin/
            
            git clone https://github.com/HalFrgrd/flyline.git /tmp/flyline
            cd /tmp/flyline && cargo build --release --locked
            cp target/release/libflyline.so /tmp/bin/
            
            CARGO_HOME=/tmp/cargo cargo install --root /tmp/build uv
            cp /tmp/build/bin/uv* /tmp/bin/
modules:
  - type: copy
    from: rust-build
    src: /tmp/bin/yazi
    dest: /usr/bin/yazi
  - type: copy
    from: rust-build
    src: /tmp/bin/ya
    dest: /usr/bin/ya
  - type: copy
    from: rust-build
    src: /tmp/bin/libflyline.so
    dest: /usr/lib/bash/libflyline.so
  - type: copy
    from: rust-build
    src: /tmp/bin/uv
    dest: /usr/bin/uv
  - type: copy
    from: rust-build
    src: /tmp/bin/uvx
    dest: /usr/bin/uvx
  - from-file: i/v/dnf.yml
  - from-file: i/v/scripts.yml
  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - sshd.service
  - type: signing
