name: dev
description: Celestial Uprising --- magrathea 
base-image: ghcr.io/celestial-uprising/mini
image-version: latest


modules:


    - type: os-release
      properties:
        VARIANT: "dev"


    - type: akmods
      install:
        - kvmfr
        - v4l2loopback


    - type: kargs
      kargs:
        - zfs.zfs_arc_max=17179869184
        - pcie_aspm=off


    - type: dnf
      install:
        install-weak-deps: false
        packages:
          - qemu-system-x86
          - qemu-system-aarch64
          - edk2-aarch64
          - qemu-system-riscv
          - qemu-img
          - qemu-audio-pipewire
          - virglrenderer
          - qemu-device-display-virtio-gpu-gl
          - qemu-ui-opengl
          - qemu-audio-spice
          - qemu-char-spice
          - qemu-device-display-qxl
          - spice-gtk
          - libguestfs-tools
          - virt-install
          - virt-top
          - libvirt
          - libvirt-daemon-qemu
          - libvirt-daemon-driver-secret
          - libvirt-daemon-driver-nodedev
          - libvirt-daemon-driver-interface
          - libvirt-daemon-driver-nwfilter
          - libvirt-daemon-config-network
          - libvirt-daemon-driver-network
          - libvirt-daemon-driver-storage
          - libvirt-daemon-driver-storage-zfs


    - type: files
      files:
        - source: 99-cpu-governor.rules
          destination: /etc/udev/rules.d/99-cpu-governor.rules
        - source: 99-workstation-perf.conf
          destination: /etc/sysctl.d/99-workstation-perf.conf


    - type: wayblue-signing
      source: local
