## KITTY'S GOT CLAWS ##
shell_integration enabled
term xterm-256color
scrollback_lines 10000
copy_on_select yes
strip_trailing_spaces smart

font_size 9.0
cursor_shape block
cursor_blink_interval 1

window_padding_width 0
background_opacity 0.5
hide_window_decorations yes

# Key bindings for common actions
map ctrl+n new_window
map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0
map ctrl+tab select_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 0

# Tab configuration
tab_bar_style powerline
tab_bar_align left
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #1a1110

tab_bar_background              #1a1110

active_tab_foreground           #000000
active_tab_background           #ffb4ab
active_tab_font_style           bold

inactive_tab_foreground         #d8c2bf
inactive_tab_background         #1a1110
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
cursor #f1dedc
cursor_text_color #d8c2bf

foreground            #f1dedc
background            #1a1110
selection_foreground  #000000
selection_background  #f9dedc
url_color             #ffb4ab

color0   #1a1110
color1   #ff7472
color2   #99ff7f
color3   #ffe472
color4   #f29c92
color5   #76362e
color6   #ffb4ab
color7   #fff1ef
color8   #a59a99
color9   #ffa09f
color10  #b8ffa5
color11  #ffeea5
color12  #ffbfb7
color13  #ffcac4
color14  #ffddd9
color15  #fff9f8
